import Fastify from "fastify"; import helmet from "@fastify/helmet"; import cors from "@fastify/cors"; import cookie from "@fastify/cookie"; import rateLimit from "@fastify/rate-limit"; import { PrismaClient } from "@prisma/client"; import argon2 from "argon2"; import { randomUUID } from "node:crypto"; import { z } from "zod"; import { config } from "./config.js"; import { hashToken, opaqueToken, signAccess, signPlayback, verifyAccess } from "./security.js";
const prisma=new PrismaClient(); const app=Fastify({logger:{level:config.NODE_ENV==="production"?"info":"debug",redact:["req.headers.authorization","req.headers.cookie","res.headers.set-cookie","body.password","body.token"]},genReqId:()=>randomUUID(),trustProxy:config.NODE_ENV==="production"?1:false});
await app.register(helmet,{global:true}); await app.register(cors,{origin:config.ADMIN_ORIGIN,credentials:true}); await app.register(cookie); await app.register(rateLimit,{max:100,timeWindow:"1 minute"});
app.setErrorHandler((error,req,reply)=>{req.log.error({err:error},"request failed"); const normalized=error as {statusCode?:number;message?:string}; const status=normalized.statusCode??500; reply.status(status).send({error:{code:status===500?"INTERNAL_ERROR":"REQUEST_ERROR",message:status===500?"Unexpected server error":normalized.message??"Request failed",requestId:req.id}})});
async function viewer(req:any,reply:any){const raw=req.headers.authorization?.replace(/^Bearer /,""); if(!raw)return reply.code(401).send({error:{code:"UNAUTHENTICATED",message:"Authentication required",requestId:req.id}}); try{req.auth=await verifyAccess(raw)}catch{return reply.code(401).send({error:{code:"TOKEN_INVALID",message:"Session expired",requestId:req.id}})}}
app.get("/health",async()=>({status:"ok"})); app.get("/ready",async(_r,reply)=>{try{await prisma.$queryRaw`SELECT 1`; return {status:"ready"}}catch{return reply.code(503).send({status:"not-ready"})}});
app.post("/api/v1/auth/register",{config:{rateLimit:{max:5,timeWindow:"15 minutes"}}},async(req,reply)=>{if(!config.REGISTRATION_ENABLED)return reply.code(403).send({error:{code:"REGISTRATION_DISABLED",message:"Registration is currently unavailable",requestId:req.id}}); const b=z.object({email:z.string().email(),password:z.string().min(12).max(128),displayName:z.string().min(2).max(80)}).parse(req.body); const passwordHash=await argon2.hash(b.password,{type:argon2.argon2id}); const user=await prisma.user.create({data:{email:b.email.toLowerCase(),displayName:b.displayName,passwordHash,role:"VIEWER"}}); return reply.code(201).send({id:user.id})});
app.post("/api/v1/auth/login",{config:{rateLimit:{max:8,timeWindow:"15 minutes"}}},async(req,reply)=>{const b=z.object({email:z.string().email(),password:z.string(),deviceId:z.string().min(8)}).parse(req.body); const user=await prisma.user.findUnique({where:{email:b.email.toLowerCase()}}); if(!user||user.status!=="ACTIVE"||!await argon2.verify(user.passwordHash,b.password))return reply.code(401).send({error:{code:"INVALID_CREDENTIALS",message:"Email or password is incorrect",requestId:req.id}}); const refresh=opaqueToken(); await prisma.refreshSession.create({data:{userId:user.id,deviceId:b.deviceId,tokenHash:hashToken(refresh),expiresAt:new Date(Date.now()+30*864e5)}}); return {accessToken:await signAccess(user.id,user.role),refreshToken:refresh,user:{id:user.id,email:user.email,displayName:user.displayName,role:user.role}}});
app.get("/api/v1/account/me",{preHandler:viewer},async(req:any)=>prisma.user.findUnique({where:{id:req.auth.sub as string},select:{id:true,email:true,displayName:true,role:true,status:true}}));
app.get("/api/v1/catalog",{preHandler:viewer},async()=>({rails:await prisma.collection.findMany({where:{published:true},orderBy:{sortOrder:"asc"},include:{items:{orderBy:{sortOrder:"asc"},include:{movie:true,series:true}}}})}));
app.get("/api/v1/search",{preHandler:viewer},async(req:any)=>{const q=z.object({q:z.string().min(2).max(100)}).parse(req.query).q; return prisma.movie.findMany({where:{status:"PUBLISHED",OR:[{title:{contains:q,mode:"insensitive"}},{synopsis:{contains:q,mode:"insensitive"}}]},take:30})});
app.post("/api/v1/playback/sessions",{preHandler:viewer,config:{rateLimit:{max:20,timeWindow:"1 minute"}}},async(req:any,reply)=>{const b=z.object({videoId:z.string().uuid(),deviceId:z.string().min(8),riskSignals:z.array(z.string()).default([])}).parse(req.body); const user=await prisma.user.findUniqueOrThrow({where:{id:req.auth.sub as string}}); if(user.status!=="ACTIVE")return reply.code(403).send({error:{code:"ACCOUNT_BLOCKED",message:"Playback unavailable",requestId:req.id}}); const asset=await prisma.videoAsset.findFirst({where:{id:b.videoId,state:"READY",OR:[{movie:{status:"PUBLISHED"}},{episode:{status:"PUBLISHED"}}]}}); if(!asset)return reply.code(404).send({error:{code:"VIDEO_UNAVAILABLE",message:"Video is unavailable",requestId:req.id}}); const active=await prisma.playbackSession.count({where:{userId:user.id,revokedAt:null,expiresAt:{gt:new Date()}}}); if(active>=config.MAX_CONCURRENT_STREAMS)return reply.code(409).send({error:{code:"STREAM_LIMIT",message:"Concurrent stream limit reached",requestId:req.id}}); const sid=randomUUID(), expiresAt=new Date(Date.now()+config.PLAYBACK_SESSION_TTL_SECONDS*1000); const token=await signPlayback({sub:user.id,sid,videoId:asset.id,deviceId:b.deviceId}); await prisma.playbackSession.create({data:{id:sid,userId:user.id,videoAssetId:asset.id,deviceId:b.deviceId,expiresAt,riskSignals:b.riskSignals}}); return {sessionId:sid,manifestUrl:`/api/v1/media/${asset.id}/manifest?pt=${token}`,headers:{"X-Playback-Session":sid},watermark:{text:`${user.id.slice(0,4)}••${sid.slice(-4)}`,opacity:.22,moveEverySeconds:18},expiresAt:expiresAt.toISOString()}});
await app.listen({host:"0.0.0.0",port:4000});
